export interface Product {
  id: number;
  name: string;
  description: string;
  images: string[];
  price: number;
  availability: number;
}

export const products: Product[] = [
  {
    id: 23,
    name: 'Curcuma',
    description: 'Originaire des forêts malgaches.',
    images: [
      'src/assets/products/curcuma1.jpg',
      'src/assets/products/curcuma2.jpg',
    ],
    price: 14327,
    availability: 39,
  },
  {
    id: 24,
    name: 'Gingembre',
    description: 'Utilisé en cosmétique et bien-être.',
    images: ['/gingembre1.jpg', '/gingembre2.jpg'],
    price: 8646,
    availability: 39,
  },
  {
    id: 41,
    name: 'Tamarin',
    description: 'Originaire des forêts malgaches.',
    images: ['/tamarin1.jpg', '/tamarin2.jpg'],
    price: 17698,
    availability: 39,
  },
  {
    id: 15,
    name: 'Caféier',
    description: 'Plante médicinale aux nombreuses vertus.',
    images: ['/caféier1.jpg', '/caféier2.jpg'],
    price: 14527,
    availability: 38,
  },
  {
    id: 47,
    name: 'Artemisia',
    description: 'Utilisé en cosmétique et bien-être.',
    images: ['/artemisia1.jpg', '/artemisia2.jpg'],
    price: 11901,
    availability: 38,
  },
  {
    id: 35,
    name: 'Basilic sacré',
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ['/basilic_sacré1.jpg', '/basilic_sacré2.jpg'],
    price: 17563,
    availability: 37,
  },
  {
    id: 37,
    name: 'Pandanus',
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ['/pandanus1.jpg', '/pandanus2.jpg'],
    price: 18321,
    availability: 37,
  },
  {
    id: 49,
    name: 'Voanio',
    description: 'Plante médicinale aux nombreuses vertus.',
    images: ['/voanio1.jpg', '/voanio2.jpg'],
    price: 13060,
    availability: 36,
  },
  {
    id: 6,
    name: 'Saro',
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ['/saro1.jpg', '/saro2.jpg'],
    price: 13203,
    availability: 35,
  },
  {
    id: 13,
    name: 'Niaouli',
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ['/niaouli1.jpg', '/niaouli2.jpg'],
    price: 10323,
    availability: 34,
  },
  {
    id: 29,
    name: 'Mandravasarotra',
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ['/mandravasarotra1.jpg', '/mandravasarotra2.jpg'],
    price: 16244,
    availability: 34,
  },
  {
    id: 40,
    name: 'Fenouil',
    description: 'Utilisé en cosmétique et bien-être.',
    images: ['/fenouil1.jpg', '/fenouil2.jpg'],
    price: 18956,
    availability: 32,
  },
  {
    id: 42,
    name: 'Banane',
    description: 'Très populaire pour son arôme naturel.',
    images: ['/banane1.jpg', '/banane2.jpg'],
    price: 14652,
    availability: 32,
  },
  {
    id: 3,
    name: 'Ylang Ylang',
    description: 'Originaire des forêts malgaches.',
    images: ['/ylang_ylang1.jpg', '/ylang_ylang2.jpg'],
    price: 15612,
    availability: 31,
  },
  {
    id: 2,
    name: 'Baobab',
    description: 'Plante médicinale aux nombreuses vertus.',
    images: ['/baobab1.jpg', '/baobab2.jpg'],
    price: 17750,
    availability: 30,
  },
  {
    id: 39,
    name: 'Maniguette',
    description: 'Originaire des forêts malgaches.',
    images: ['/maniguette1.jpg', '/maniguette2.jpg'],
    price: 12011,
    availability: 30,
  },
  {
    id: 9,
    name: 'Combava',
    description: 'Utilisé en cosmétique et bien-être.',
    images: ['/combava1.jpg', '/combava2.jpg'],
    price: 19268,
    availability: 29,
  },
  {
    id: 11,
    name: 'Girofle',
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ['/girofle1.jpg', '/girofle2.jpg'],
    price: 12678,
    availability: 29,
  },
  {
    id: 22,
    name: 'Citronnelle',
    description: 'Très populaire pour son arôme naturel.',
    images: ['/citronnelle1.jpg', '/citronnelle2.jpg'],
    price: 17156,
    availability: 29,
  },
  {
    id: 48,
    name: 'Fanjan',
    description: 'Originaire des forêts malgaches.',
    images: ['/fanjan1.jpg', '/fanjan2.jpg'],
    price: 16714,
    availability: 28,
  },
  {
    id: 7,
    name: 'Katrafay',
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ['/katrafay1.jpg', '/katrafay2.jpg'],
    price: 18040,
    availability: 27,
  },
  {
    id: 17,
    name: "Zeste d'orange",
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ["/zeste_d'orange1.jpg", "/zeste_d'orange2.jpg"],
    price: 10203,
    availability: 27,
  },
  {
    id: 20,
    name: 'Patchouli',
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ['/patchouli1.jpg', '/patchouli2.jpg'],
    price: 17672,
    availability: 27,
  },
  {
    id: 30,
    name: 'Tsiperifery',
    description: 'Originaire des forêts malgaches.',
    images: ['/tsiperifery1.jpg', '/tsiperifery2.jpg'],
    price: 19865,
    availability: 26,
  },
  {
    id: 4,
    name: 'Vahona',
    description: 'Plante médicinale aux nombreuses vertus.',
    images: ['/vahona1.jpg', '/vahona2.jpg'],
    price: 11093,
    availability: 25,
  },
  {
    id: 25,
    name: 'Papaye',
    description: 'Originaire des forêts malgaches.',
    images: ['/papaye1.jpg', '/papaye2.jpg'],
    price: 17555,
    availability: 25,
  },
  {
    id: 19,
    name: 'Vanille',
    description: 'Plante médicinale aux nombreuses vertus.',
    images: ['/vanille1.jpg', '/vanille2.jpg'],
    price: 17750,
    availability: 20,
  },
  {
    id: 36,
    name: 'Laurier',
    description: 'Originaire des forêts malgaches.',
    images: ['/laurier1.jpg', '/laurier2.jpg'],
    price: 14007,
    availability: 20,
  },
  {
    id: 5,
    name: 'Masonjoany',
    description: 'Utilisé en cosmétique et bien-être.',
    images: ['/masonjoany1.jpg', '/masonjoany2.jpg'],
    price: 19180,
    availability: 19,
  },
  {
    id: 10,
    name: 'Eucalyptus',
    description: 'Plante médicinale aux nombreuses vertus.',
    images: ['/eucalyptus1.jpg', '/eucalyptus2.jpg'],
    price: 12274,
    availability: 18,
  },
  {
    id: 43,
    name: 'Figuier',
    description: 'Plante médicinale aux nombreuses vertus.',
    images: ['/figuier1.jpg', '/figuier2.jpg'],
    price: 12834,
    availability: 18,
  },
  {
    id: 38,
    name: 'Voamadilo',
    description: 'Originaire des forêts malgaches.',
    images: ['/voamadilo1.jpg', '/voamadilo2.jpg'],
    price: 18333,
    availability: 17,
  },
  {
    id: 44,
    name: 'Palmier',
    description: 'Très populaire pour son arôme naturel.',
    images: ['/palmier1.jpg', '/palmier2.jpg'],
    price: 14610,
    availability: 17,
  },
  {
    id: 33,
    name: 'Aloe Vera',
    description: 'Originaire des forêts malgaches.',
    images: ['/aloe_vera1.jpg', '/aloe_vera2.jpg'],
    price: 17837,
    availability: 16,
  },
  {
    id: 28,
    name: 'Tamanu',
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ['/tamanu1.jpg', '/tamanu2.jpg'],
    price: 9203,
    availability: 15,
  },
  {
    id: 46,
    name: "Ranon'ala",
    description: 'Originaire des forêts malgaches.',
    images: ["/ranon'ala1.jpg", "/ranon'ala2.jpg"],
    price: 14617,
    availability: 15,
  },
  {
    id: 31,
    name: 'Raphia',
    description: 'Plante médicinale aux nombreuses vertus.',
    images: ['/raphia1.jpg', '/raphia2.jpg'],
    price: 8580,
    availability: 14,
  },
  {
    id: 50,
    name: 'Endro',
    description: 'Plante médicinale aux nombreuses vertus.',
    images: ['/endro1.jpg', '/endro2.jpg'],
    price: 16247,
    availability: 14,
  },
  {
    id: 1,
    name: 'Ravintsara',
    description: 'Très populaire pour son arôme naturel.',
    images: ['/ravintsara1.jpg', '/ravintsara2.jpg'],
    price: 16995,
    availability: 13,
  },
  {
    id: 12,
    name: 'Vetyver',
    description: 'Plante médicinale aux nombreuses vertus.',
    images: ['/vetyver1.jpg', '/vetyver2.jpg'],
    price: 18173,
    availability: 13,
  },
  {
    id: 45,
    name: 'Kalanchoe',
    description: 'Utilisé en cosmétique et bien-être.',
    images: ['/kalanchoe1.jpg', '/kalanchoe2.jpg'],
    price: 19472,
    availability: 13,
  },
  {
    id: 34,
    name: 'Santal',
    description: 'Plante médicinale aux nombreuses vertus.',
    images: ['/santal1.jpg', '/santal2.jpg'],
    price: 18222,
    availability: 12,
  },
  {
    id: 27,
    name: 'Jasmin',
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ['/jasmin1.jpg', '/jasmin2.jpg'],
    price: 18467,
    availability: 11,
  },
  {
    id: 14,
    name: 'Romy',
    description: 'Originaire des forêts malgaches.',
    images: ['/romy1.jpg', '/romy2.jpg'],
    price: 8756,
    availability: 10,
  },
  {
    id: 32,
    name: 'Ravina',
    description: 'Appréciée pour ses propriétés apaisantes.',
    images: ['/ravina1.jpg', '/ravina2.jpg'],
    price: 18537,
    availability: 9,
  },
  {
    id: 18,
    name: 'Litchi',
    description: 'Très populaire pour son arôme naturel.',
    images: ['/litchi1.jpg', '/litchi2.jpg'],
    price: 15279,
    availability: 8,
  },
  {
    id: 8,
    name: 'Cinnamomum',
    description: 'Originaire des forêts malgaches.',
    images: ['/cinnamomum1.jpg', '/cinnamomum2.jpg'],
    price: 14022,
    availability: 7,
  },
  {
    id: 26,
    name: 'Moringa',
    description: 'Utilisé en cosmétique et bien-être.',
    images: ['/moringa1.jpg', '/moringa2.jpg'],
    price: 17651,
    availability: 6,
  },
  {
    id: 16,
    name: 'Cannelle',
    description: 'Originaire des forêts malgaches.',
    images: ['/cannelle1.jpg', '/cannelle2.jpg'],
    price: 15007,
    availability: 5,
  },
  {
    id: 21,
    name: 'Menthe',
    description: 'Originaire des forêts malgaches.',
    images: ['/menthe1.jpg', '/menthe2.jpg'],
    price: 17444,
    availability: 5,
  },
];
