/* tslint:disable */
/* eslint-disable */
/**
 * SNGF API
 * API for managing plants, seeds, events, blogs, testimonials, and orders for the SNGF website
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderItemsInner
 */
export interface OrderItemsInner {
    /**
     * 
     * @type {string}
     * @memberof OrderItemsInner
     */
    plantId: string;
    /**
     * 
     * @type {number}
     * @memberof OrderItemsInner
     */
    quantity: number;
}

/**
 * Check if a given object implements the OrderItemsInner interface.
 */
export function instanceOfOrderItemsInner(value: object): value is OrderItemsInner {
    if (!('plantId' in value) || value['plantId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function OrderItemsInnerFromJSON(json: any): OrderItemsInner {
    return OrderItemsInnerFromJSONTyped(json, false);
}

export function OrderItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'plantId': json['plant_id'],
        'quantity': json['quantity'],
    };
}

export function OrderItemsInnerToJSON(json: any): OrderItemsInner {
    return OrderItemsInnerToJSONTyped(json, false);
}

export function OrderItemsInnerToJSONTyped(value?: OrderItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plant_id': value['plantId'],
        'quantity': value['quantity'],
    };
}

