/* tslint:disable */
/* eslint-disable */
/**
 * SNGF API
 * API for managing plants, seeds, events, blogs, testimonials, and orders for the SNGF website
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Plant
 */
export interface Plant {
    /**
     * 
     * @type {number}
     * @memberof Plant
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Plant
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Plant
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof Plant
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Plant
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof Plant
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof Plant
     */
    status: PlantStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Plant
     */
    imageUrl?: string;
}


/**
 * @export
 */
export const PlantStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;
export type PlantStatusEnum = typeof PlantStatusEnum[keyof typeof PlantStatusEnum];


/**
 * Check if a given object implements the Plant interface.
 */
export function instanceOfPlant(value: object): value is Plant {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PlantFromJSON(json: any): Plant {
    return PlantFromJSONTyped(json, false);
}

export function PlantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Plant {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'],
        'quantity': json['quantity'],
        'status': json['status'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
    };
}

export function PlantToJSON(json: any): Plant {
    return PlantToJSONTyped(json, false);
}

export function PlantToJSONTyped(value?: Omit<Plant, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'description': value['description'],
        'price': value['price'],
        'quantity': value['quantity'],
        'status': value['status'],
        'image_url': value['imageUrl'],
    };
}

