/* tslint:disable */
/* eslint-disable */
/**
 * SNGF API
 * API for managing plants, seeds, events, blogs, testimonials, and orders for the SNGF website
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadFile
 */
export interface UploadFile {
    /**
     * 
     * @type {string}
     * @memberof UploadFile
     */
    fileToUpload: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFile
     */
    id: string;
    /**
     * name without extension
     * @type {string}
     * @memberof UploadFile
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UploadFile
     */
    type: string;
    /**
     * 
     * @type {Date}
     * @memberof UploadFile
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the UploadFile interface.
 */
export function instanceOfUploadFile(value: object): value is UploadFile {
    if (!('fileToUpload' in value) || value['fileToUpload'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function UploadFileFromJSON(json: any): UploadFile {
    return UploadFileFromJSONTyped(json, false);
}

export function UploadFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFile {
    if (json == null) {
        return json;
    }
    return {
        
        'fileToUpload': json['fileToUpload'],
        'id': json['id'],
        'name': json['name'],
        'type': json['type'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function UploadFileToJSON(json: any): UploadFile {
    return UploadFileToJSONTyped(json, false);
}

export function UploadFileToJSONTyped(value?: UploadFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileToUpload': value['fileToUpload'],
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

