/* tslint:disable */
/* eslint-disable */
/**
 * SNGF API
 * API for managing plants, seeds, events, blogs, testimonials, and orders for the SNGF website
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Blog,
} from '../models/index';
import {
    BlogFromJSON,
    BlogToJSON,
} from '../models/index';

export interface CreateBlogRequest {
    blog: Blog;
}

export interface DeleteBlogRequest {
    id: number;
}

export interface GetBlogByIDRequest {
    id: number;
}

export interface GetListBlogRequest {
    keyword?: string;
    status?: GetListBlogStatusEnum;
    page?: number;
    pageSize?: number;
}

export interface UpdateBlogRequest {
    id: number;
    blog: Blog;
}

/**
 * 
 */
export class BlogsApi extends runtime.BaseAPI {

    /**
     * Add a new blog article.
     * Add a new blog
     */
    async createBlogRaw(requestParameters: CreateBlogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['blog'] == null) {
            throw new runtime.RequiredError(
                'blog',
                'Required parameter "blog" was null or undefined when calling createBlog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/blogs/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BlogToJSON(requestParameters['blog']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add a new blog article.
     * Add a new blog
     */
    async createBlog(requestParameters: CreateBlogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createBlogRaw(requestParameters, initOverrides);
    }

    /**
     * Delete a blog article by its ID.
     * Delete a blog
     */
    async deleteBlogRaw(requestParameters: DeleteBlogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteBlog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blogs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a blog article by its ID.
     * Delete a blog
     */
    async deleteBlog(requestParameters: DeleteBlogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBlogRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve a single blog article by its ID.
     * Get blog by ID
     */
    async getBlogByIDRaw(requestParameters: GetBlogByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blog>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getBlogByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blogs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlogFromJSON(jsonValue));
    }

    /**
     * Retrieve a single blog article by its ID.
     * Get blog by ID
     */
    async getBlogByID(requestParameters: GetBlogByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blog> {
        const response = await this.getBlogByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a filtered list of blog articles.
     * Get list of blogs
     */
    async getListBlogRaw(requestParameters: GetListBlogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Blog>>> {
        const queryParameters: any = {};

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blogs/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BlogFromJSON));
    }

    /**
     * Retrieve a filtered list of blog articles.
     * Get list of blogs
     */
    async getListBlog(requestParameters: GetListBlogRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Blog>> {
        const response = await this.getListBlogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing blog article.
     * Update a blog
     */
    async updateBlogRaw(requestParameters: UpdateBlogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateBlog().'
            );
        }

        if (requestParameters['blog'] == null) {
            throw new runtime.RequiredError(
                'blog',
                'Required parameter "blog" was null or undefined when calling updateBlog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/blogs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BlogToJSON(requestParameters['blog']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update an existing blog article.
     * Update a blog
     */
    async updateBlog(requestParameters: UpdateBlogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateBlogRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const GetListBlogStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;
export type GetListBlogStatusEnum = typeof GetListBlogStatusEnum[keyof typeof GetListBlogStatusEnum];
