/* tslint:disable */
/* eslint-disable */
/**
 * SNGF API
 * API for managing plants, seeds, events, blogs, testimonials, and orders for the SNGF website
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Plant,
} from '../models/index';
import {
    PlantFromJSON,
    PlantToJSON,
} from '../models/index';

export interface CrupdatePlantRequest {
    id: number;
    plant: Plant;
}

export interface GetListPlantRequest {
    name?: string;
    type?: string;
    category?: GetListPlantCategoryEnum;
    size?: GetListPlantSizeEnum;
    unit?: string;
    status?: GetListPlantStatusEnum;
    operatorId?: number;
    page?: number;
    pageSize?: number;
}

export interface GetPlantByIDRequest {
    id: number;
}

/**
 * 
 */
export class PlantsApi extends runtime.BaseAPI {

    /**
     * Update an existing plant or seed\'s information.
     * Update a plant or seed
     */
    async crupdatePlantRaw(requestParameters: CrupdatePlantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling crupdatePlant().'
            );
        }

        if (requestParameters['plant'] == null) {
            throw new runtime.RequiredError(
                'plant',
                'Required parameter "plant" was null or undefined when calling crupdatePlant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/plants/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PlantToJSON(requestParameters['plant']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update an existing plant or seed\'s information.
     * Update a plant or seed
     */
    async crupdatePlant(requestParameters: CrupdatePlantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.crupdatePlantRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve a filtered list of active plants and seeds.
     * Get list of plants and seeds
     */
    async getListPlantRaw(requestParameters: GetListPlantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Plant>>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['unit'] != null) {
            queryParameters['unit'] = requestParameters['unit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['operatorId'] != null) {
            queryParameters['operator_id'] = requestParameters['operatorId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plants/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlantFromJSON));
    }

    /**
     * Retrieve a filtered list of active plants and seeds.
     * Get list of plants and seeds
     */
    async getListPlant(requestParameters: GetListPlantRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Plant>> {
        const response = await this.getListPlantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a single plant or seed by its ID.
     * Get plant or seed by ID
     */
    async getPlantByIDRaw(requestParameters: GetPlantByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Plant>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPlantByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plants/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlantFromJSON(jsonValue));
    }

    /**
     * Retrieve a single plant or seed by its ID.
     * Get plant or seed by ID
     */
    async getPlantByID(requestParameters: GetPlantByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Plant> {
        const response = await this.getPlantByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetListPlantCategoryEnum = {
    Seed: 'SEED',
    Plant: 'PLANT'
} as const;
export type GetListPlantCategoryEnum = typeof GetListPlantCategoryEnum[keyof typeof GetListPlantCategoryEnum];
/**
 * @export
 */
export const GetListPlantSizeEnum = {
    Xs: 'XS',
    S: 'S',
    M: 'M',
    L: 'L',
    Xl: 'XL'
} as const;
export type GetListPlantSizeEnum = typeof GetListPlantSizeEnum[keyof typeof GetListPlantSizeEnum];
/**
 * @export
 */
export const GetListPlantStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;
export type GetListPlantStatusEnum = typeof GetListPlantStatusEnum[keyof typeof GetListPlantStatusEnum];
