name: Generate OpenAPI Client

on:
  repository_dispatch:
    types: [generate-client]

jobs:
  generate-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v2

      - name: Checkout API repository
        uses: actions/checkout@v2
        with:
          repository: SNGF-official/api  # Remplace par l'URL du repo API
          path: api-spec

      # Installer OpenAPI Generator CLI via npm
      - name: Install OpenAPI Generator CLI
        run: |
          npm install @openapitools/openapi-generator-cli -g

      # Vérifier le contenu du répertoire API spec
      - name: List files in API spec directory
        run: |
          ls -l api-spec/docs

      # Générer le client avec OpenAPI Generator
      - name: Generate client with OpenAPI Generator
        run: |
          openapi-generator-cli generate -i api-spec/docs/api.yaml -g typescript-fetch -o ./generated-client

      # Configurer Git pour push avec le token
      - name: Set up Git for push
        run: |
          git config --global user.email "rabenaly3@gmail.com"
          git config --global user.name "YlanDecode"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/SNGF-official/web.git

      # Vérifier l'URL du remote Git
      - name: Check remote URL
        run: |
          git remote -v  # Vérifie que l'URL est bien configurée

      # Commit et push du client généré
      - name: Commit and push generated client
        run: |
          git add generated-client
          git commit -m "Update generated OpenAPI client"
          git push
