name: Generate OpenAPI Client

on:
  repository_dispatch:
    types: [generate-client]

jobs:
  generate-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v2

      - name: Checkout API repository
        uses: actions/checkout@v2
        with:
          repository: SNGF-official/API  # Remplace par l'URL de ton repo API
          path: api-spec

      # Télécharger et exécuter OpenAPI Generator
      - name: Download and run OpenAPI Generator CLI
        run: |
          curl -L https://github.com/OpenAPITools/openapi-generator/releases/download/v6.0.0/openapi-generator-cli-v6.0.0.jar -o openapi-generator-cli.jar
          java -jar openapi-generator-cli.jar generate -i api-spec/openapi.yaml -g typescript-fetch -o ./generated-client

      # Commit et push du client généré
      - name: Commit and push generated client
        run: |
          git add generated-client
          git commit -m "Update generated OpenAPI client"
          git push
