name: Generate OpenAPI Client

on:
  repository_dispatch:
    types: [generate-client]

jobs:
  generate-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v2

      - name: Checkout API repository
        uses: actions/checkout@v2
        with:
          repository: SNGF-official/API  # Remplace par l'URL de ton repo API
          path: api-spec

      # Installer OpenAPI Generator via npm
      - name: Install OpenAPI Generator CLI
        run: |
          npm install @openapitools/openapi-generator-cli -g

      # Générer le client avec OpenAPI Generator
      - name: Generate client with OpenAPI Generator
        run: |
          openapi-generator-cli generate -i api-spec/openapi.yaml -g typescript-fetch -o ./generated-client

      # Commit et push du client généré
      - name: Commit and push generated client
        run: |
          git add generated-client
          git commit -m "Update generated OpenAPI client"
          git push
