name: Generate OpenAPI Client

on:
  repository_dispatch:
    types: [generate-client]

jobs:
  generate-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v2

      - name: Checkout API repository
        uses: actions/checkout@v2
        with:
          repository: SNGF-official/api  # Remplace par l'URL du repo API
          path: api-spec  # Le fichier sera téléchargé dans le dossier api-spec

      # Installer OpenAPI Generator CLI via npm
      - name: Install OpenAPI Generator CLI
        run: |
          npm install @openapitools/openapi-generator-cli -g

      # Vérifier le contenu du répertoire API spec
      - name: List files in API spec directory
        run: |
          ls -l api-spec/docs  # Vérifie si api.yaml est bien dans docs/

      # Générer le client avec OpenAPI Generator
      - name: Generate client with OpenAPI Generator
        run: |
          openapi-generator-cli generate -i api-spec/docs/api.yaml -g typescript-fetch -o ./generated-client  # Assure-toi du chemin complet

      # Commit et push du client généré
      - name: Commit and push generated client
        run: |
          git config --global user.email rabenaly3@gmail.com
          git config --global user.name YlanDecode
          git add generated-client
          git commit -m "Update generated OpenAPI client"
          git push
